version: "3.9"

services:
  imagesizator-web-server:
    container_name: imagesizator
    build:
      context: ../../
      dockerfile: ./docker/dockerfiles/prod-web-dockerfile/Dockerfile
    volumes:
      - ../../database:/var/www/imagesizator/database
      - ../../www:/var/www/imagesizator/www
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./build_config/.env
    stop_grace_period: 3s
    networks:
      static-network:
        ipv4_address: 10.22.13.1

networks:
  static-network:
    name: imagesizator-network
    ipam:
      config:
        - subnet: 10.22.13.0/24