version: "3.9"

services:
  imagesizator-web-server:
    container_name: imagesizator
    build:
      context: ../../
      dockerfile: ./docker/dockerfiles/prod-web-dockerfile/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./build_config/.env
    stop_grace_period: 3s
    volumes:
      - ../../static:/srv/imagesizator_service/static
      - ../../www:/srv/imagesizator_service/www
    ports:
        - "8000:8000"
    networks:
      static-network:
        ipv4_address: 10.22.26.2
  nginx:
    container_name: imagesizator-nginx
    build:
      context: ../dockerfiles/nginx
      dockerfile: Dockerfile
    image: imagesizator-nginx:v1.0
    restart: unless-stopped
    depends_on:
      - imagesizator-web-server
    volumes:
      - ../../static:/srv/imagesizator_service/static
    ports:
        - "80:80"
    networks:
      static-network:
        ipv4_address: 10.22.26.5
  redis-service:
    container_name: redis
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    stop_grace_period: 3s
    networks:
      static-network:
        ipv4_address: 10.22.26.3
  scheduler:
    container_name: scheduler
    build:
      context: ../../
      dockerfile: ./docker/dockerfiles/scheduler/Dockerfile
    restart: unless-stopped
    depends_on:
      - imagesizator-web-server
    networks:
      static-network:
        ipv4_address: 10.22.26.4

networks:
  static-network:
    name: imagesizator-network
    ipam:
      config:
        - subnet: 10.22.26.0/24
