default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast

      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files

      - id: detect-private-key
        exclude: ^.*\b(.example.py)\b.*$

      - id: check-docstring-first
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
  - repo: https://github.com/psf/black
    rev: 22.12.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        exclude: ^.*\b(migrations|static)\b.*$
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-bugbear",
          "flake8-comprehensions",
          "flake8-mutable",
          "flake8-print",
          "flake8-simplify",
        ]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
