# Generated by Django 4.0.4 on 2022-06-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, null=True, verbose_name='Fecha de creación')),
                ('key', models.CharField(help_text='Ingrese el nombre del parámetro', max_length=100)),
                ('value', models.TextField(default='', help_text='Ingrese el valor del parámetro')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
