# Generated by Django 4.0.4 on 2022-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesizatorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False, null=True, verbose_name='Created date')),
                ('path', models.TextField(help_text='File path')),
                ('bytes_string', models.TextField(default='', help_text='Image as a bytes string')),
            ],
            options={
                'verbose_name': 'Imagesizator file',
                'verbose_name_plural': 'Imagesizator files',
            },
        ),
        migrations.CreateModel(
            name='ImagesizatorTemporaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(editable=False, verbose_name='Expiration date (valid until)')),
            ],
            options={
                'verbose_name': 'Temporary file',
                'verbose_name_plural': 'Temporary files',
            },
        ),
    ]
