# Generated by Django 4.0.4 on 2022-07-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagesizatorfile_imagesizatortemporaryfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesizatortemporaryfile',
            name='id',
        ),
        migrations.AddField(
            model_name='imagesizatortemporaryfile',
            name='imagesizatorfile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.imagesizatorfile'),
            preserve_default=False,
        ),
    ]
