# Generated by Django 4.0.4 on 2022-07-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagesizatortemporaryfile_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesizatortemporaryfile',
            name='expiration_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Expiration date (valid until)'),
        ),
    ]
