# Generated by Django 4.0.4 on 2023-07-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagesizatorfile_bytes_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesizatorStaticFile',
            fields=[
                ('imagesizatorfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.imagesizatorfile')),
            ],
            options={
                'verbose_name': 'Static file',
                'verbose_name_plural': 'Static files',
            },
            bases=('api.imagesizatorfile',),
        ),
        migrations.AddField(
            model_name='imagesizatorfile',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
