# Generated by Django 4.0.4 on 2023-07-31 18:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imagesizatorstaticfile_imagesizatorfile_is_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesizatorfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 31, 18, 16, 19, 884551, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
