# Generated by Django 4.0.4 on 2023-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_imagesizatorimagefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesizatorfile',
            name='file_name',
            field=models.CharField(default='file', max_length=100),
            preserve_default=False,
        ),
    ]
